name: Deploy to staging VPS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/mark/FizzUp
          git fetch origin
          git reset --hard origin/${{ github.ref_name }}
      
      - name: Rebuild and restart API + Web only
        run: |
          cd /home/mark/FizzUp
          docker-compose --env-file .env.staging -f docker-compose.staging.yaml up -d --build --force-recreate fizzup_api fizzup_web_app
