name: Deploy to staging VPS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/mark/FizzUp
          git fetch origin
          git reset --hard origin/${{ github.ref_name }}

      - name: Fix permissions
        run: sudo chown -R mark:mark /home/mark/FizzUp

      - name: Restart Docker
        run: |
          cd /home/mark/FizzUp
          ./scripts/docker-start.sh ${{ github.ref_name }}
